version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DBURL: dpg-d1r0596r433s739n535g-a.oregon-postgres.render.com
      DBNAME: libraryapp_nnph
      DBUSERNAME: libraryapp_nnph_user
      DBPASSWORD: PzFnIciIus4i3nmErXVvoIxNuQVURVDg

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: libraryapp_nnph_user
      POSTGRES_PASSWORD: PzFnIciIus4i3nmErXVvoIxNuQVURVDg
      POSTGRES_DB: libraryapp_nnph
