version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    # Harici PostgreSQL kullanıldığı için depends_on kaldırıldı
    environment:
      DBURL: ${DBURL}
      DBNAME: ${DBNAME}
      DBUSERNAME: ${DBUSERNAME}
      DBPASSWORD: ${DBPASSWORD}

  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: libraryapp_nnph_user
  #     POSTGRES_PASSWORD: PzFnIciIus4i3nmErXVvoIxNuQVURVDg
  #     POSTGRES_DB: libraryapp_nnph
